Repository Default-Cube-Studios/Movement-Template, pull requests merged in 2022-12, with the labels that each got.

#6 Stamina system
  Assets/Fonts.meta
  Assets/Fonts/EdgeOfTheGalaxyRegular-OVEa6 SDF.asset
  Assets/Fonts/EdgeOfTheGalaxyRegular-OVEa6 SDF.asset.meta
  Assets/Fonts/EdgeOfTheGalaxyRegular-OVEa6.otf
  Assets/Fonts/EdgeOfTheGalaxyRegular-OVEa6.otf.meta
  Assets/Prefabs.meta
  Assets/Prefabs/Player.prefab
  Assets/Prefabs/Player.prefab.meta
  Assets/Scenes/MainLevel.unity
  Assets/Scripts/CameraRotation.cs
  Assets/Scripts/PlayerMovement.cs
  Assets/Scripts/ResetPlayer.cs
  Assets/Scripts/ResetPlayer.cs.meta
  Assets/Scripts/StaminaBar.cs
  Assets/Scripts/StaminaBar.cs.meta
  ProjectSettings/TagManager.asset
  UserSettings/Layouts/CurrentMaximizeLayout.dwlt
Labels: Redo, Update

#16 Migration to new Input System
  Assets/Input.meta
  Assets/Input/PlayerInputSystem.inputactions
  Assets/Input/PlayerInputSystem.inputactions.meta
  Assets/Materials/Sticky.physicMaterial
  Assets/Materials/Sticky.physicMaterial.meta
  Assets/Prefabs/Player.prefab
  Assets/Scenes/MainLevel.unity
  Assets/Scripts/CameraRotation.cs
  Assets/Scripts/PlayerMovement.cs
  Assets/Scripts/ResetPlayer.cs
  Assets/Scripts/ResetPlayer.cs.meta
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/ProjectSettings.asset
  UserSettings/Layouts/default-2022.dwlt
Labels: Redo, Update

#17 New Player class
  Assets/Prefabs/Player.prefab
  Assets/Prefabs/Player.prefab.meta
  Assets/Scenes/MainLevel.unity
  Assets/Scripts/CameraRotation.cs
  Assets/Scripts/Player.cs
  Assets/Scripts/Player.cs.meta
  Assets/Scripts/PlayerMovement.cs
  Assets/Scripts/StaminaBar.cs
  ProjectSettings/ProjectSettings.asset
  UserSettings/Layouts/CurrentMaximizeLayout.dwlt
Labels: Redo, Update

#22 Sensitivity Increased
  Assets/Input/PlayerInputSystem.inputactions
  Assets/Scenes/MainLevel.unity
Labels: Bug, Defect, Update

#14 MIT License
  LICENSE
Labels: Update
